# - - - - - - - - - - - - - - #
# EasterEggHunt Configuration #
# - - - - - - - - - - - - - - #
# --- eggHuntEnabled ---
# boolean. when set to false, plugin will do nothing.
# --- apiEndpoint ---
# The score tracking API endpoint without a trailing slash
# --- apiKey ---
# API key for score tracking for this server
# --- hunts ---
# WorldGuard regions where egg hunts are taking place. Use LOWER-CASE letters in world and region names.
# For example,
#   hunts:
#     world_name:
#       region_name:
#         enabled: true

eggHuntEnabled: false
apiEndpoint: ''
apiKey: ''
hunts: []